### ISSUE TITLE
Expanding g:news_headlines_sources

### ISSUE THREAD

**Issue by for-coursera** [skamsie/vim-news-headlines#1]
Would be great to make `g:news_headlines_sources` not only understand sources but work with more detailed entries like `{'domain': 'wsj.com', 'q': 'bitcoin'}, {'source': 'cnn', 'date': 'today'}, {'q': 'apple', 'sortBy': 'popularity'}, {'source': 'bbc-news', 'top-headlines': 'on'}`, and so on, as shown in NewsAPI [documentation](https://newsapi.org/docs/endpoints).

**Comment by skamsie** [comment]
Good point, will look into it at some point 👍

**Comment by skamsie** [comment]
I checked their api documentation and there are some nice features but they are outside of the scope of this plugin. I want to keep it simple and the intention is not to be a 1 on 1 match for apinews.org. Closing this issue for now, but thanks for the suggestion.

**Comment by skamsie** [comment]
@for-coursera I added something similar to what you wanted. Please update and check the new documentation on how to use.

PR: https://github.com/skamsie/vim-news-headlines/pull/3

**Comment by for-coursera** [comment]
Adding support for `domains` to `g:news_headlines_topics` would make it even better :). 

(The point is, if we just search [everything](https://newsapi.org/docs/endpoints/everything) for a topic, some results seem to be omitted: try first a general search for Apple or Bitcoin, for example, and then try the same search but limiting it to `domains=wsj.com`: you should see the results, which were absent in the first query.)

**Comment by skamsie** [comment]
It is more complex than this, it also depends on your plan and sorting algorithm (which is in fact more like a filter). For developer plan the results will be limited. I am only showing the results for the last two days and showing only most recent 10 articles anyways.

As I said before the intention is not to make this plugin a 1 on 1 interface for newsapi.org. I think it is very powerful already.
